# Timeout in seconds that Limine will use before automatically booting.
timeout: 5

# The entry name that will be displayed in the boot menu.
/CAT
    protocol: limine
    # Oh wait I forgot this exists lol :3
    path: boot():/boot/cat_kernel.elf

    module_path: boot():/FONT.F16
    module_cmdline: FONT

    module_path: boot():/boot/init.bin
    module_cmdline: INIT